apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: aj0e5d1ga-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ff87d3c52a.xwcq.p3.openshiftapps.com/rhtap/rhtap-qe:3e433259291e7a47b3ff4416da7e9acb5bfa0116@sha256:5ef8b28d9859cf395b32ab44446a209167593a8ae8c1dd924d8cbf465bccd299
          name: container-image
