apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aj0e5d1ga-nodejs
  janus-idp.io/tekton: aj0e5d1ga-nodejs
  backstage.io/kubernetes-id: aj0e5d1ga-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aj0e5d1ga-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
