apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: aj0e5d1ga-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aj0e5d1ga-nodejs 
  name: aj0e5d1ga-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: aj0e5d1ga-nodejs
    weight: 100 
