apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aj0e5d1ga-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aj0e5d1ga-nodejs 
  name: aj0e5d1ga-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: aj0e5d1ga-nodejs 
